/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Dsl360RuntimeModule extends AbstractDsl360RuntimeModule {
}
