/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Dsl360StandaloneSetup extends Dsl360StandaloneSetupGenerated {

	def static void doSetup() {
		new Dsl360StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
