/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ide.contentassist.antlr;

import co.betinrubio.ide.contentassist.antlr.internal.InternalDsl360Parser;
import co.betinrubio.services.Dsl360GrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class Dsl360Parser extends AbstractContentAssistParser {

	@Inject
	private Dsl360GrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDsl360Parser createParser() {
		InternalDsl360Parser result = new InternalDsl360Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
					put(grammarAccess.getProyectoAccess().getGroup(), "rule__Proyecto__Group__0");
					put(grammarAccess.getProyectoAccess().getGroup_10(), "rule__Proyecto__Group_10__0");
					put(grammarAccess.getTourAccess().getGroup(), "rule__Tour__Group__0");
					put(grammarAccess.getTourAccess().getGroup_10(), "rule__Tour__Group_10__0");
					put(grammarAccess.getPanoramaAccess().getGroup(), "rule__Panorama__Group__0");
					put(grammarAccess.getPanoramaAccess().getGroup_6(), "rule__Panorama__Group_6__0");
					put(grammarAccess.getPanoramaAccess().getGroup_11(), "rule__Panorama__Group_11__0");
					put(grammarAccess.getHotspotAccess().getGroup(), "rule__Hotspot__Group__0");
					put(grammarAccess.getPosicionAccess().getGroup(), "rule__Posicion__Group__0");
					put(grammarAccess.getRotacionAccess().getGroup(), "rule__Rotacion__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
					put(grammarAccess.getProyectoAccess().getNameAssignment_4(), "rule__Proyecto__NameAssignment_4");
					put(grammarAccess.getProyectoAccess().getTouresAssignment_9(), "rule__Proyecto__TouresAssignment_9");
					put(grammarAccess.getProyectoAccess().getTouresAssignment_10_1(), "rule__Proyecto__TouresAssignment_10_1");
					put(grammarAccess.getTourAccess().getNameAssignment_4(), "rule__Tour__NameAssignment_4");
					put(grammarAccess.getTourAccess().getPanoramasAssignment_9(), "rule__Tour__PanoramasAssignment_9");
					put(grammarAccess.getTourAccess().getPanoramasAssignment_10_1(), "rule__Tour__PanoramasAssignment_10_1");
					put(grammarAccess.getPanoramaAccess().getNameAssignment_4(), "rule__Panorama__NameAssignment_4");
					put(grammarAccess.getPanoramaAccess().getImagenAssignment_6_2(), "rule__Panorama__ImagenAssignment_6_2");
					put(grammarAccess.getPanoramaAccess().getHotspotsAssignment_10(), "rule__Panorama__HotspotsAssignment_10");
					put(grammarAccess.getPanoramaAccess().getHotspotsAssignment_11_1(), "rule__Panorama__HotspotsAssignment_11_1");
					put(grammarAccess.getHotspotAccess().getNameAssignment_4(), "rule__Hotspot__NameAssignment_4");
					put(grammarAccess.getHotspotAccess().getDestinoAssignment_8(), "rule__Hotspot__DestinoAssignment_8");
					put(grammarAccess.getHotspotAccess().getPosicionAssignment_12(), "rule__Hotspot__PosicionAssignment_12");
					put(grammarAccess.getHotspotAccess().getRotacionAssignment_16(), "rule__Hotspot__RotacionAssignment_16");
					put(grammarAccess.getPosicionAccess().getXAssignment_4(), "rule__Posicion__XAssignment_4");
					put(grammarAccess.getPosicionAccess().getYAssignment_8(), "rule__Posicion__YAssignment_8");
					put(grammarAccess.getPosicionAccess().getZAssignment_12(), "rule__Posicion__ZAssignment_12");
					put(grammarAccess.getRotacionAccess().getXAssignment_4(), "rule__Rotacion__XAssignment_4");
					put(grammarAccess.getRotacionAccess().getYAssignment_8(), "rule__Rotacion__YAssignment_8");
					put(grammarAccess.getRotacionAccess().getZAssignment_12(), "rule__Rotacion__ZAssignment_12");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Dsl360GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Dsl360GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
