/**
 * generated by Xtext 2.12.0
 */
package co.betinrubio;

import co.betinrubio.AbstractDsl360RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Dsl360RuntimeModule extends AbstractDsl360RuntimeModule {
}
