/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ide

import co.betinrubio.Dsl360RuntimeModule
import co.betinrubio.Dsl360StandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Dsl360IdeSetup extends Dsl360StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Dsl360RuntimeModule, new Dsl360IdeModule))
	}
	
}
