/**
 * generated by Xtext 2.12.0
 */
package co.betinrubio.validation;

import co.betinrubio.validation.AbstractDsl360Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Dsl360Validator extends AbstractDsl360Validator {
}
