/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ui;

import co.betinrubio.dsl360.ui.internal.Dsl360Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Dsl360ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Dsl360Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Dsl360Activator.getInstance().getInjector(Dsl360Activator.CO_BETINRUBIO_DSL360);
	}
	
}
