/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDsl360ScopeProvider extends DelegatingScopeProvider {
}
