/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ui.tests;

import co.betinrubio.dsl360.ui.internal.Dsl360Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Dsl360UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Dsl360Activator.getInstance().getInjector("co.betinrubio.Dsl360");
	}

}
