/**
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ui.contentassist;

import co.betinrubio.ui.contentassist.AbstractDsl360ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Dsl360ProposalProvider extends AbstractDsl360ProposalProvider {
}
