/**
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ide;

import co.betinrubio.ide.AbstractDsl360IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Dsl360IdeModule extends AbstractDsl360IdeModule {
}
