/**
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ide;

import co.betinrubio.Dsl360RuntimeModule;
import co.betinrubio.Dsl360StandaloneSetup;
import co.betinrubio.ide.Dsl360IdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Dsl360IdeSetup extends Dsl360StandaloneSetup {
  @Override
  public Injector createInjector() {
    Dsl360RuntimeModule _dsl360RuntimeModule = new Dsl360RuntimeModule();
    Dsl360IdeModule _dsl360IdeModule = new Dsl360IdeModule();
    return Guice.createInjector(Modules2.mixin(_dsl360RuntimeModule, _dsl360IdeModule));
  }
}
