/*
 * generated by Xtext 2.12.0
 */
package co.betinrubio.parser.antlr;

import co.betinrubio.parser.antlr.internal.InternalDsl360Parser;
import co.betinrubio.services.Dsl360GrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Dsl360Parser extends AbstractAntlrParser {

	@Inject
	private Dsl360GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDsl360Parser createParser(XtextTokenStream stream) {
		return new InternalDsl360Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Proyecto";
	}

	public Dsl360GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Dsl360GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
