/**
 * generated by Xtext 2.12.0
 */
package co.betinrubio.ui;

import co.betinrubio.ui.AbstractDsl360UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Dsl360UiModule extends AbstractDsl360UiModule {
  public Dsl360UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
