/**
 *
 * $Id$
 */
package metamodel360.validation;

import metamodel360.Panorama;
import metamodel360.Posicion;
import metamodel360.Rotacion;

/**
 * A sample validator interface for {@link metamodel360.Hotspot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HotspotValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateNombre(String value);
	boolean validatePosicion(Posicion value);
	boolean validateRotacion(Rotacion value);
	boolean validateDestino(Panorama value);
}
