/**
 *
 * $Id$
 */
package metamodel360.validation;

import metamodel360.Tour;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link metamodel360.Proyecto}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProyectoValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateNombre(String value);
	boolean validateToures(EList<Tour> value);
}
